//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veterinary_clinic.AddBd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reception
    {
        public int id { get; set; }
        public int id_animals { get; set; }
        public int id_Doc { get; set; }
        public System.DateTime Date { get; set; }
        public string Dicription { get; set; }
        public int lsDelete { get; set; }
    
        public virtual Animals Animals { get; set; }
        public virtual Doct Doct { get; set; }
    }
}
